version: '3.9'

services:
  helper:
    image: ubuntu:20.04
    network_mode: service:capturer
    command:
      - sleep
      - infinity

  sender:
    image: 'ghcr.io/instrumentisto/nmap:7.94-r4'
    network_mode: service:capturer
    entrypoint:
      - /bin/sh
      - -c  # 203.0.113.0/24 is TEST-NET-3
      - 'nping --udp --dest-port 1666 --data-length 23 --count 0 --rate 3 receiver'

  receiver:
    build:
      dockerfile: Dockerfile_receiver
    entrypoint:
      - /bin/sh
      - -c
      - 'netcat -l -u 1666 | hexdump -C'

  capturer:
    build:
      context: .
    ports:
      - 9108:9108  # Metrics
    environment:
      MODE: capture
      DEVICE: eth0
      FILTER: not udp port 7386
      RELAY_ENDPOINT: 'collector:7386'

  collector:
    build:
      context: .
    # ports:
    #   - 9108:9108  # Metrics
    environment:
      MODE: collect
      COLLECT_ENDPOINT: ':7386'
