networks:
  payload:

services:
  helper:
    build:
      dockerfile: Dockerfile_helper
    network_mode: service:collector
    command:
      - sleep
      - infinity

  receiver:
    build:
      dockerfile: Dockerfile_receiver
    network_mode: service:capturer
    entrypoint:
      - /bin/sh
      - -c
      - 'netcat -l -u 1666 >/dev/null'

  sender:
    depends_on:
      - receiver
    build:
      dockerfile: Dockerfile_sender
    networks:
      - payload
    entrypoint:
      - /bin/sh
      - -c  # 203.0.113.0/24 is TEST-NET-3
      - 'nping --udp --source-port random --dest-port 1666 --data-length 23 --count 0 --rate 1 receiver'

  capturer:
    build:
      context: .
    networks:
      - payload
    ports:
      - 9108:9108  # Metrics
    environment:
      MODE: capture
      DEVICE: eth0
      FILTER: #not udp port 7386
      RELAY_ENDPOINT: 'collector:7386'

  collector:
    build:
      context: .
    networks:
      - payload
    # ports:
    #   - 9108:9108  # Metrics
    environment:
      MODE: collect
      COLLECT_ENDPOINT: ':7386'
