services:
  helper:
    build:
      dockerfile: Dockerfile_helper
    network_mode: host
    command:
      - sleep
      - infinity

  receiver:
    build:
      dockerfile: Dockerfile_receiver
    network_mode: host
    entrypoint:
      - /bin/sh
      - -c
      - 'netcat -v -l -u 1666 >/dev/null'

  sender:
    depends_on:
      - receiver
    build:
      dockerfile: Dockerfile_sender
    network_mode: host
    entrypoint:
      - /bin/sh
      - -c  # 203.0.113.0/24 is TEST-NET-3
      - 'nping --udp --source-port random --dest-port 1666 --data-length 23 --count 0 --rate 1 localhost'

  capturer-lo:
    build:
      context: .
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      MODE: capture
      DEVICE: lo
      FILTER: #not udp port 7386
      RELAY_ENDPOINT: '127.0.0.2:7386'
      METRICS_ADDRPORT: ':9109'

  capturer-enp5s0:
    build:
      context: .
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      MODE: capture
      DEVICE: enp5s0
      FILTER: #not udp port 7386
      RELAY_ENDPOINT: '127.0.0.2:7386'
      METRICS_ADDRPORT: ':9110'

  collector:
    build:
      context: .
    network_mode: host
    environment:
      MODE: collect
      COLLECT_ENDPOINT: '127.0.0.2:7386'
      METRICS_ADDRPORT: ':9111'
