name: Go

on: [push]

env:
  REGISTRY: ghcr.io
  PLATFORMS: amd64,arm64

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Install and initialize dependencies
        run: go get .
      - name: Unit test
        run: go test -v .
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          # See https://github.com/docker/metadata-action#latest-tag
          tags: |
            type=raw,value=${{ github.ref_name }},enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ steps.meta.outputs.tags }}
      #- name: Integration test
      #  run: |
      #    docker compose build
      #    docker compose up --exit-code-from integration-test
